### ISSUE TITLE
Makefile for test

### ISSUE THREAD

**Issue by spth** [freetdi/gala#1]
I suggest to add a Makefile in tests that builds an executes all tests; this would allow gala users to easily execute the tests to spot problems on their systems (and to decide if an issue they encounter in their own programs is likely to be with gala on their system vs. a bug in their own code).

Philipp

**Comment by felix-salfelder** [comment]
testing is now documented in `README`. please let me know if that's okay (for now)

**Comment by spth** [comment]
Seem fine to me. Maybe those messages about "incomplete" shouldn't be in the test output, since it is not clear if they indicate that the tests do not yet have full coverage vs. the test not being completely executed due to some runtime issue.

Philipp

**Comment by felix-salfelder** [comment]
valid point. i have updated the `README` accordingly.
