### ISSUE TITLE
Failure to compile with Microsoft C because of intrinsic naming

### ISSUE THREAD

**Issue by jbrandwood** [freetdi/gala#8]
The VisualStudio C compiler uses different names for intrinsics than GCC, and you need to include <intrin.h>.

VS2019 also complains that BSET_DYNAMIC is declared as a "struct" in some places, and as a "class" in other places.

This patch fixes both the intrinsics, and it changes BSET_DYNAMIC usage to be consistent (as a "class").

[vs2019.patch](https://github.com/freetdi/gala/files/14961238/vs2019.patch)

**Comment by felix-salfelder** [comment]
On Fri, Apr 12, 2024 at 09:39:12AM -0700, jbrandwood wrote:
> This patch fixes both the intrinsics, and it changes BSET_DYNAMIC usage to be consistent (as a "class").

Thanks John.

I rephrased it a bit, it's in the popcount branch. Still incomplete,
but in a different way. Anyway, the platform header did not exist at the
time of writing.

Happy to proceed with this for now, if it works. Or just get rid of it
entirely and require C++20?

popcount may be too generic a name, and I wonder if I once called it
"numberofones" in order to avoid a clash.

cheers
felix

**Comment by jbrandwood** [comment]
The popcount branch works fine, thanks! :-)

FWIW, I had to enable C++20 in VS2019 anyway because cbset.h includes the "bit" header which doesn't exist before C++20, and VS2019 was complaining about it.

If you take a look at boost/config/detail/suffix.hpp, they put a "__has_include()" guard around their usage of that header.

It looks like you put a comment in platform.h wondering why there's a check for _WIN64 when using __popcnt64() ... well according to Microsoft, the 64-bit version of the popcnt instruction doesn't exist when compiling for a 32-bit x86 CPU.

**Comment by felix-salfelder** [comment]
On Sat, Apr 13, 2024 at 08:05:38AM -0700, jbrandwood wrote:
> The popcount branch works fine, thanks! :-)
> 
> FWIW, I had to enable C++20 in VS2019 anyway because cbset.h includes
> the <bit> header which doesn't exist before C++20, and VS2019 was
> complaining about it.

Thanks for testing.

In that case, I believe "using std::popcount;" (if C++20 is enabled)
deals with VS situation in a better and also portable way.

(I remember there was a performance issue with defaulting to C++20, so
this may be more work.)

> It looks like you put a comment in platform.h wondering why there's a
> check for _WIN64 when using __popcnt64() ... well according to
> Microsoft, the 64-bit version of the popcnt instruction doesn't exist
> when compiling for a 32-bit x86 CPU.

I prefer to remove the convoluted logic. Will require another iteration,
but may save time in the long run...

**Comment by felix-salfelder** [comment]
Done in 11603890b44. Please close this if it works, or tell me if it does not... Thanks for your time.

**Comment by jbrandwood** [comment]
Sorry for the delay in responding, I've been totally focused on a different project fo the last few weeks.

Rev 1160389 is working fine, thanks! I'll close this issue now.
